# Generated by Django 4.1.5 on 2023-03-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('lastname', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=250, null=True)),
                ('mobile', models.IntegerField(blank=True, default=None, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('dob', models.DateField(blank=True, default=None, max_length=250, null=True)),
                ('address', models.TextField(blank=True, default=None, max_length=250, null=True)),
                ('districts', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('branches', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('qualification', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('specialization', models.CharField(blank=True, default=None, max_length=250, null=True)),
            ],
        ),
    ]
