# Generated by Django 4.1.5 on 2023-03-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_alter_loan_branch_alter_loan_district_delete_branch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
