# Generated by Django 4.1.5 on 2023-03-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_team_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.TextField(max_length=250)),
                ('team_image', models.ImageField(upload_to='pics')),
                ('position', models.CharField(max_length=250)),
            ],
        ),
    ]
