# Generated by Django 4.1.5 on 2023-03-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0010_alter_customer_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer',
            new_name='customer_testmonials',
        ),
    ]
